### ISSUE TITLE
Middle-mousedown drag scrolling

### ISSUE THREAD

**Issue by blah238** [UziTech/atom-scroll-editor-on-middle-click#1]
First off great work in solving this glaring UX oversight in Atom!

I'm not sure if it's doable, but I'd like to see this (or another package) enable scrolling while simply holding down the middle mouse button and dragging (rather than clicking once to enable scrolling and again to disable), as supported in browsers like Firefox and Chrome. For me this is usually the quickest way to get around a page or document as I only need to click once instead of twice.

Thanks!

**Comment by UziTech** [comment]
Good idea. I added a setting for it in v0.3.0
