### ISSUE TITLE
Support both hold-to-scroll and click-to-scroll

### ISSUE THREAD

**Issue by blah238** [UziTech/atom-scroll-editor-on-middle-click#2]
Thanks for adding the hold-to-scroll option in the fix to #1!

However, rather than having to choose between hold-to-scroll or click-to-scroll in the options, I'd like to be able to use either at any time.

I think both interactions have their uses, i.e. hold-to-scroll for quickly getting around and click-to-scroll for slowly panning down while reading.

Most browsers will let you do this, Firefox and Chrome I know for sure.

Thanks again!

**Comment by UziTech** [comment]
Ah, nice catch. I didn't know the browsers did this. I will see if i can get it working.

**Comment by UziTech** [comment]
Fixed in v0.4.0

That was easier than I thought it would be

**Comment by blah238** [comment]
Sweet, thanks!
