### ISSUE TITLE
Won't work with my version of Atom

### ISSUE THREAD

**Issue by davidhealey** [UziTech/atom-scroll-editor-on-middle-click#3]
It says version must satisfy >=1.21.0

**Comment by UziTech** [comment]
That is the earliest version it has been tested on. Is there a reason you need it to work on older versions?

**Comment by davidhealey** [comment]
Actually I didn't realise I wasn't using the latest version. But I downloaded you extension manually and installed it and it worked just fine anyway. I'm going to update to the newest version, thanks.
