### ISSUE TITLE
Middle Click Pastes in Linux

### ISSUE THREAD

**Issue by nehoffman** [UziTech/atom-scroll-editor-on-middle-click#5]
Because middle-clicking pastes in Linux, this will cause whatever is in the clipboard to be dumped out whenever I try to scroll. If you have some way to disable that with your extension that would be very helpful. Otherwise, I cannot use your extension without repeatedly running xclip -i /dev/null to clear out the clipboard.

**Comment by UziTech** [comment]
I don't have an easy way to test on linux or time to setup a VM, but if you would like to submit a pull request I would be happy to merge it. 👍

**Comment by nehoffman** [comment]
Works for me! I'll see what I can do.

**Comment by UziTech** [comment]
It could be something as simple as setting the mousedown event options to `passive: false` and adding `e.preventDefault()` to the `startScroll` function

**Comment by nehoffman** [comment]
Turns out it wasn't quite that simple, but I put a pull request in. I'm a little new to using Github so let me know if I missed an important step.

**Comment by UziTech** [comment]
This should be fixed in v0.6.0
