### ISSUE TITLE
Breaks closing tabs by click on MMB

### ISSUE THREAD

**Issue by AlexWayfer** [UziTech/atom-scroll-editor-on-middle-click#9]
Hello!

With this extension I can't close tabs with MMB click.

Thanks.

**Comment by UziTech** [comment]
It seems to work for me. The package should only change the click event when it is inside a text editor.

What os are you on?

**Comment by AlexWayfer** [comment]
It doesn't work even with disabled extension and in `--safe` mode… So, it's not package-related issue. Sorry.
